port: ":4002"
readbuffer: 1024
writebuffer: 1024
messagestore: false
messageexpire: 0
messageoverflow: 0
userdatebase: 0
errorlog: ""
debuglog: ""
allowguests: true
databaseaddress: "localhost:6379"
databasepass: ""
databaseuser: 0
