// Code generated by protoc-gen-go.
// source: v1.proto
// DO NOT EDIT!

/*
Package v1 is a generated protocol buffer package.

It is generated from these files:
	v1.proto

It has these top-level messages:
	Meta
	Signatures
	Timestamp
	ClientMessage
	ServerMessage
	StreamMessage
	NewConversationRequest
	Conversation
*/
package v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Meta provides the meta data for Tiberious messages.
type Meta struct {
	Time *Timestamp `protobuf:"bytes,1,opt,name=time" json:"time,omitempty"`
}

func (m *Meta) Reset()                    { *m = Meta{} }
func (m *Meta) String() string            { return proto.CompactTextString(m) }
func (*Meta) ProtoMessage()               {}
func (*Meta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Meta) GetTime() *Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

// Signatures houses the signatures for a message.
type Signatures struct {
	OriginalSigner   []byte   `protobuf:"bytes,1,opt,name=original_signer,json=originalSigner,proto3" json:"original_signer,omitempty"`
	SecondarySigners [][]byte `protobuf:"bytes,2,rep,name=secondary_signers,json=secondarySigners,proto3" json:"secondary_signers,omitempty"`
}

func (m *Signatures) Reset()                    { *m = Signatures{} }
func (m *Signatures) String() string            { return proto.CompactTextString(m) }
func (*Signatures) ProtoMessage()               {}
func (*Signatures) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Signatures) GetOriginalSigner() []byte {
	if m != nil {
		return m.OriginalSigner
	}
	return nil
}

func (m *Signatures) GetSecondarySigners() [][]byte {
	if m != nil {
		return m.SecondarySigners
	}
	return nil
}

// SEE: google/protobuf/timestamp.proto
type Timestamp struct {
	// Represents seconds of UTC time since Unix epoch
	// 1970-01-01T00:00:00Z. Must be from from 0001-01-01T00:00:00Z to
	// 9999-12-31T23:59:59Z inclusive.
	Seconds int64 `protobuf:"varint,1,opt,name=seconds" json:"seconds,omitempty"`
	// Non-negative fractions of a second at nanosecond resolution. Negative
	// second values with fractions must still have non-negative nanos values
	// that count forward in time. Must be from 0 to 999,999,999
	// inclusive.
	Nanos int32 `protobuf:"varint,2,opt,name=nanos" json:"nanos,omitempty"`
}

func (m *Timestamp) Reset()                    { *m = Timestamp{} }
func (m *Timestamp) String() string            { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()               {}
func (*Timestamp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Timestamp) GetSeconds() int64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *Timestamp) GetNanos() int32 {
	if m != nil {
		return m.Nanos
	}
	return 0
}

// ClientMessage is a message sent from a client to a server, this may
// contain information for the server or another client.
type ClientMessage struct {
	Meta           *Meta       `protobuf:"bytes,1,opt,name=meta" json:"meta,omitempty"`
	Signatures     *Signatures `protobuf:"bytes,2,opt,name=signatures" json:"signatures,omitempty"`
	ConversationId int64       `protobuf:"varint,10,opt,name=conversation_id,json=conversationId" json:"conversation_id,omitempty"`
	Data           []byte      `protobuf:"bytes,11,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *ClientMessage) Reset()                    { *m = ClientMessage{} }
func (m *ClientMessage) String() string            { return proto.CompactTextString(m) }
func (*ClientMessage) ProtoMessage()               {}
func (*ClientMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ClientMessage) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *ClientMessage) GetSignatures() *Signatures {
	if m != nil {
		return m.Signatures
	}
	return nil
}

func (m *ClientMessage) GetConversationId() int64 {
	if m != nil {
		return m.ConversationId
	}
	return 0
}

func (m *ClientMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// ServerMessage is a message sent from a server to a client, this will
// contain information from the server for the client.
type ServerMessage struct {
	Meta *Meta  `protobuf:"bytes,1,opt,name=meta" json:"meta,omitempty"`
	Data string `protobuf:"bytes,10,opt,name=data" json:"data,omitempty"`
}

func (m *ServerMessage) Reset()                    { *m = ServerMessage{} }
func (m *ServerMessage) String() string            { return proto.CompactTextString(m) }
func (*ServerMessage) ProtoMessage()               {}
func (*ServerMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ServerMessage) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *ServerMessage) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// StreamMessage wraps all the valid types that may be passed over a
// Tiberious gRPC stream.
type StreamMessage struct {
	// Types that are valid to be assigned to StreamMessage:
	//	*StreamMessage_ServerMessage
	//	*StreamMessage_ClientMessage
	StreamMessage isStreamMessage_StreamMessage `protobuf_oneof:"stream_message"`
}

func (m *StreamMessage) Reset()                    { *m = StreamMessage{} }
func (m *StreamMessage) String() string            { return proto.CompactTextString(m) }
func (*StreamMessage) ProtoMessage()               {}
func (*StreamMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type isStreamMessage_StreamMessage interface {
	isStreamMessage_StreamMessage()
}

type StreamMessage_ServerMessage struct {
	ServerMessage *ServerMessage `protobuf:"bytes,10,opt,name=server_message,json=serverMessage,oneof"`
}
type StreamMessage_ClientMessage struct {
	ClientMessage *ClientMessage `protobuf:"bytes,11,opt,name=client_message,json=clientMessage,oneof"`
}

func (*StreamMessage_ServerMessage) isStreamMessage_StreamMessage() {}
func (*StreamMessage_ClientMessage) isStreamMessage_StreamMessage() {}

func (m *StreamMessage) GetStreamMessage() isStreamMessage_StreamMessage {
	if m != nil {
		return m.StreamMessage
	}
	return nil
}

func (m *StreamMessage) GetServerMessage() *ServerMessage {
	if x, ok := m.GetStreamMessage().(*StreamMessage_ServerMessage); ok {
		return x.ServerMessage
	}
	return nil
}

func (m *StreamMessage) GetClientMessage() *ClientMessage {
	if x, ok := m.GetStreamMessage().(*StreamMessage_ClientMessage); ok {
		return x.ClientMessage
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*StreamMessage) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _StreamMessage_OneofMarshaler, _StreamMessage_OneofUnmarshaler, _StreamMessage_OneofSizer, []interface{}{
		(*StreamMessage_ServerMessage)(nil),
		(*StreamMessage_ClientMessage)(nil),
	}
}

func _StreamMessage_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*StreamMessage)
	// stream_message
	switch x := m.StreamMessage.(type) {
	case *StreamMessage_ServerMessage:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ServerMessage); err != nil {
			return err
		}
	case *StreamMessage_ClientMessage:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ClientMessage); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("StreamMessage.StreamMessage has unexpected type %T", x)
	}
	return nil
}

func _StreamMessage_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*StreamMessage)
	switch tag {
	case 10: // stream_message.server_message
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ServerMessage)
		err := b.DecodeMessage(msg)
		m.StreamMessage = &StreamMessage_ServerMessage{msg}
		return true, err
	case 11: // stream_message.client_message
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ClientMessage)
		err := b.DecodeMessage(msg)
		m.StreamMessage = &StreamMessage_ClientMessage{msg}
		return true, err
	default:
		return false, nil
	}
}

func _StreamMessage_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*StreamMessage)
	// stream_message
	switch x := m.StreamMessage.(type) {
	case *StreamMessage_ServerMessage:
		s := proto.Size(x.ServerMessage)
		n += proto.SizeVarint(10<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *StreamMessage_ClientMessage:
		s := proto.Size(x.ClientMessage)
		n += proto.SizeVarint(11<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// NewConversationRequest is a requet to start a new Conversation.
type NewConversationRequest struct {
	Meta       *Meta       `protobuf:"bytes,1,opt,name=meta" json:"meta,omitempty"`
	Signatures *Signatures `protobuf:"bytes,2,opt,name=signatures" json:"signatures,omitempty"`
	// participants should be obfuscated, either using a temporary ID
	// or similar...
	Participants []string `protobuf:"bytes,10,rep,name=participants" json:"participants,omitempty"`
}

func (m *NewConversationRequest) Reset()                    { *m = NewConversationRequest{} }
func (m *NewConversationRequest) String() string            { return proto.CompactTextString(m) }
func (*NewConversationRequest) ProtoMessage()               {}
func (*NewConversationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *NewConversationRequest) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *NewConversationRequest) GetSignatures() *Signatures {
	if m != nil {
		return m.Signatures
	}
	return nil
}

func (m *NewConversationRequest) GetParticipants() []string {
	if m != nil {
		return m.Participants
	}
	return nil
}

// Conversation represents a Tiberious conversation.
type Conversation struct {
	Id         int64      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Created    *Timestamp `protobuf:"bytes,2,opt,name=created" json:"created,omitempty"`
	TimeOfLast *Timestamp `protobuf:"bytes,3,opt,name=time_of_last,json=timeOfLast" json:"time_of_last,omitempty"`
}

func (m *Conversation) Reset()                    { *m = Conversation{} }
func (m *Conversation) String() string            { return proto.CompactTextString(m) }
func (*Conversation) ProtoMessage()               {}
func (*Conversation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Conversation) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Conversation) GetCreated() *Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Conversation) GetTimeOfLast() *Timestamp {
	if m != nil {
		return m.TimeOfLast
	}
	return nil
}

func init() {
	proto.RegisterType((*Meta)(nil), "tiberious.v1.Meta")
	proto.RegisterType((*Signatures)(nil), "tiberious.v1.Signatures")
	proto.RegisterType((*Timestamp)(nil), "tiberious.v1.Timestamp")
	proto.RegisterType((*ClientMessage)(nil), "tiberious.v1.ClientMessage")
	proto.RegisterType((*ServerMessage)(nil), "tiberious.v1.ServerMessage")
	proto.RegisterType((*StreamMessage)(nil), "tiberious.v1.StreamMessage")
	proto.RegisterType((*NewConversationRequest)(nil), "tiberious.v1.NewConversationRequest")
	proto.RegisterType((*Conversation)(nil), "tiberious.v1.Conversation")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Tiberious service

type TiberiousClient interface {
	// StartStream starts a bi-directional stream.
	StartStream(ctx context.Context, opts ...grpc.CallOption) (Tiberious_StartStreamClient, error)
	// NewConversation starts a new conversation.
	NewConversation(ctx context.Context, in *NewConversationRequest, opts ...grpc.CallOption) (*Conversation, error)
}

type tiberiousClient struct {
	cc *grpc.ClientConn
}

func NewTiberiousClient(cc *grpc.ClientConn) TiberiousClient {
	return &tiberiousClient{cc}
}

func (c *tiberiousClient) StartStream(ctx context.Context, opts ...grpc.CallOption) (Tiberious_StartStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Tiberious_serviceDesc.Streams[0], c.cc, "/tiberious.v1.Tiberious/StartStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &tiberiousStartStreamClient{stream}
	return x, nil
}

type Tiberious_StartStreamClient interface {
	Send(*StreamMessage) error
	Recv() (*StreamMessage, error)
	grpc.ClientStream
}

type tiberiousStartStreamClient struct {
	grpc.ClientStream
}

func (x *tiberiousStartStreamClient) Send(m *StreamMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *tiberiousStartStreamClient) Recv() (*StreamMessage, error) {
	m := new(StreamMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *tiberiousClient) NewConversation(ctx context.Context, in *NewConversationRequest, opts ...grpc.CallOption) (*Conversation, error) {
	out := new(Conversation)
	err := grpc.Invoke(ctx, "/tiberious.v1.Tiberious/NewConversation", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Tiberious service

type TiberiousServer interface {
	// StartStream starts a bi-directional stream.
	StartStream(Tiberious_StartStreamServer) error
	// NewConversation starts a new conversation.
	NewConversation(context.Context, *NewConversationRequest) (*Conversation, error)
}

func RegisterTiberiousServer(s *grpc.Server, srv TiberiousServer) {
	s.RegisterService(&_Tiberious_serviceDesc, srv)
}

func _Tiberious_StartStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TiberiousServer).StartStream(&tiberiousStartStreamServer{stream})
}

type Tiberious_StartStreamServer interface {
	Send(*StreamMessage) error
	Recv() (*StreamMessage, error)
	grpc.ServerStream
}

type tiberiousStartStreamServer struct {
	grpc.ServerStream
}

func (x *tiberiousStartStreamServer) Send(m *StreamMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *tiberiousStartStreamServer) Recv() (*StreamMessage, error) {
	m := new(StreamMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Tiberious_NewConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TiberiousServer).NewConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tiberious.v1.Tiberious/NewConversation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TiberiousServer).NewConversation(ctx, req.(*NewConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Tiberious_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tiberious.v1.Tiberious",
	HandlerType: (*TiberiousServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewConversation",
			Handler:    _Tiberious_NewConversation_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartStream",
			Handler:       _Tiberious_StartStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "v1.proto",
}

func init() { proto.RegisterFile("v1.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 512 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x94, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x86, 0xeb, 0xb6, 0xcb, 0xd2, 0x49, 0x9a, 0x5d, 0x2c, 0x04, 0x51, 0xb9, 0x54, 0x16, 0x82,
	0x4a, 0x2b, 0x55, 0xb4, 0x7b, 0x01, 0x71, 0xdb, 0xdd, 0x03, 0x08, 0x0a, 0x92, 0x0b, 0x17, 0x2e,
	0x91, 0x9b, 0xcc, 0x56, 0x96, 0x1a, 0xa7, 0xd8, 0x6e, 0x10, 0xef, 0xc0, 0x33, 0xf0, 0x06, 0x20,
	0xf1, 0x86, 0x28, 0x4e, 0x52, 0x92, 0x6a, 0x59, 0x89, 0x0b, 0xb7, 0x78, 0xfc, 0xfb, 0xf3, 0xcc,
	0x3f, 0x9e, 0xc0, 0xdd, 0x7c, 0x36, 0xdd, 0xea, 0xcc, 0x66, 0xd4, 0xb7, 0x72, 0x85, 0x5a, 0x66,
	0x3b, 0x33, 0xcd, 0x67, 0xec, 0x1c, 0xfa, 0x0b, 0xb4, 0x82, 0x9e, 0x41, 0xdf, 0xca, 0x14, 0x43,
	0x32, 0x26, 0x13, 0x6f, 0xfe, 0x70, 0xda, 0x14, 0x4d, 0x3f, 0xc8, 0x14, 0x8d, 0x15, 0xe9, 0x96,
	0x3b, 0x11, 0x5b, 0x01, 0x2c, 0xe5, 0x5a, 0x09, 0xbb, 0xd3, 0x68, 0xe8, 0x53, 0x38, 0xc9, 0xb4,
	0x5c, 0x4b, 0x25, 0x36, 0x91, 0x91, 0x6b, 0x85, 0xda, 0x51, 0x7c, 0x1e, 0xd4, 0xe1, 0xa5, 0x8b,
	0xd2, 0x33, 0xb8, 0x67, 0x30, 0xce, 0x54, 0x22, 0xf4, 0xd7, 0x4a, 0x69, 0xc2, 0xee, 0xb8, 0x37,
	0xf1, 0xf9, 0xe9, 0x7e, 0xa3, 0xd4, 0x1a, 0xf6, 0x12, 0x06, 0xfb, 0x6b, 0x69, 0x08, 0xc7, 0xa5,
	0xc0, 0x38, 0x74, 0x8f, 0xd7, 0x4b, 0x7a, 0x1f, 0x8e, 0x94, 0x50, 0x59, 0xc1, 0x21, 0x93, 0x23,
	0x5e, 0x2e, 0xd8, 0x4f, 0x02, 0xc3, 0xcb, 0x8d, 0x44, 0x65, 0x17, 0x68, 0x8c, 0x58, 0x23, 0x7d,
	0x02, 0xfd, 0x14, 0xad, 0xa8, 0xea, 0xa3, 0xed, 0xfa, 0x0a, 0x07, 0xb8, 0xdb, 0xa7, 0xcf, 0x01,
	0xcc, 0xbe, 0x34, 0x07, 0xf5, 0xe6, 0x61, 0x5b, 0xfd, 0xa7, 0x74, 0xde, 0xd0, 0x16, 0x36, 0xc4,
	0x99, 0xca, 0x51, 0x1b, 0x61, 0x65, 0xa6, 0x22, 0x99, 0x84, 0xe0, 0x72, 0x0d, 0x9a, 0xe1, 0xd7,
	0x09, 0xa5, 0xd0, 0x4f, 0x84, 0x15, 0xa1, 0xe7, 0x4c, 0x72, 0xdf, 0xec, 0x0d, 0x0c, 0x97, 0xa8,
	0x73, 0xd4, 0xff, 0x9a, 0x6f, 0x0d, 0x2b, 0xae, 0x1a, 0x54, 0xb0, 0x1f, 0x04, 0x86, 0x4b, 0xab,
	0x51, 0xa4, 0x35, 0xed, 0x0a, 0x02, 0xe3, 0xf0, 0x51, 0x5a, 0x46, 0x9c, 0xde, 0x9b, 0x3f, 0x3a,
	0xa8, 0xac, 0x99, 0xc2, 0xab, 0x0e, 0x1f, 0x9a, 0x56, 0x4e, 0x57, 0x10, 0xc4, 0xce, 0xd4, 0x3d,
	0xc5, 0xbb, 0x89, 0xd2, 0x32, 0xbe, 0xa0, 0xc4, 0xcd, 0xc0, 0xc5, 0x29, 0x04, 0xc6, 0x25, 0x57,
	0x53, 0xd8, 0x77, 0x02, 0x0f, 0xde, 0xe1, 0x97, 0xcb, 0x86, 0x4d, 0x1c, 0x3f, 0xef, 0xd0, 0xd8,
	0xff, 0xd0, 0x36, 0x06, 0xfe, 0x56, 0x68, 0x2b, 0x63, 0xb9, 0x15, 0xca, 0x9a, 0x10, 0xc6, 0xbd,
	0xc9, 0x80, 0xb7, 0x62, 0xec, 0x1b, 0x01, 0xbf, 0x99, 0x1d, 0x0d, 0xa0, 0x2b, 0x93, 0xea, 0x29,
	0x76, 0x65, 0x42, 0x67, 0x70, 0x1c, 0x6b, 0x14, 0x16, 0x93, 0xea, 0xee, 0xbf, 0x0e, 0x50, 0xad,
	0xa3, 0x2f, 0xc0, 0x2f, 0x66, 0x29, 0xca, 0xae, 0xa3, 0x8d, 0x30, 0x36, 0xec, 0xdd, 0x7e, 0x0e,
	0x0a, 0xf1, 0xfb, 0xeb, 0xb7, 0xc2, 0xd8, 0xf9, 0x2f, 0x52, 0xcc, 0x46, 0x25, 0xa3, 0x0b, 0xf0,
	0x96, 0x56, 0x68, 0x5b, 0x76, 0x9c, 0x1e, 0xb6, 0xb4, 0xf9, 0x0e, 0x46, 0xb7, 0x6d, 0xb2, 0xce,
	0x84, 0x3c, 0x23, 0xf4, 0x23, 0x9c, 0x1c, 0xf4, 0x82, 0x3e, 0x6e, 0x9f, 0xba, 0xb9, 0x55, 0xa3,
	0xd1, 0xc1, 0x2b, 0x68, 0x48, 0x58, 0xe7, 0xa2, 0xff, 0xa9, 0x9b, 0xcf, 0x56, 0x77, 0xdc, 0x2f,
	0xe8, 0xfc, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc2, 0xeb, 0xcc, 0x43, 0x8e, 0x04, 0x00, 0x00,
}
